name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    permissions:
      contents: write
      packages: write
    uses: simplyRoba/.github/.github/workflows/rust-publish-release.yml@v1
    with:
      binary-name: pixoo-bridge
